name: Deploy to Firebase Hosting

on:
  push:
    paths:
      - 'user_cards/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: echo "${{ secrets.FIREBASE_TOKEN }}" | firebase login:ci --token "$(cat -)"

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project nfc-card-app-79464
